apiVersion: apps/v1
kind: Deployment
metadata:
  name: appauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: boussaidi/auth:latest
          ports:
            - name: auth-app-port
              containerPort: 8084